// <auto-generated />
namespace PRJ666_G7_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migrationAppUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrationAppUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "202302192232347_migrationAppUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
